apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-webapp-deployment
spec:
  replicas: 2 # You can adjust the number of desired instances
  selector:
    matchLabels:
      app: fashion-webapp
  template:
    metadata:
      labels:
        app: fashion-webapp
    spec:
      containers:
        - name: fashion-webapp-container
          image: hashfact/fashion-webapp:v0.1 # Replace with your Docker Hub image
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_ENV
              value: development # Or 'development' if needed
          # Add resource requests and limits if necessary
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 128Mi
          #   limits:
          #     cpu: 500m
          #     memory: 512Mi