apiVersion: v1
kind: Service
metadata:
  name: fashion-webapp-service
spec:
  selector:
    app: fashion-webapp
  ports:
    - protocol: TCP
      port: 80 # The port you want to expose externally
      targetPort: 5000 # The port your container is listening on
  type: LoadBalancer # Use LoadBalancer for external access in cloud environments
    # Use ClusterIP for internal access only
  # Use NodePort for exposing on each Node's IP at a static port